/**
 * log() is a function for logging messages to the console in a standard format.
 *
 * @param message The message to log
 * @returns void
 */
export function log(message: string): void {
  const time = new Date().toLocaleTimeString();
  const file = new Error().stack?.split('at ')[2].split(' ')[0];
  const maxLength = 20; // Set the desired maximum length for the file section
  const paddedFile = file?.padEnd(maxLength, ' ');
  console.log(time + ' | ' + paddedFile + '| ' + message);
}

/**
 * slopePreview() is a helper function for visualizing the terrain generated by the generateYValues() function.
 * It takes an array of y-values and prints a preview of the terrain to the console.
 *
 * @param yValues An array of y-values
 * @param maxY The maximum y-value in the array
 * @param width The width of the terrain preview
 * @param height The height of the terrain preview
 */
export default function slopePreview(
  yValues: number[],
  maxY: number,
  width: number,
  height: number
) {
  const terrain: string[][] = [];

  for (let i = 0; i < height; i++) {
    terrain[i] = [];
    for (let j = 0; j < width; j++) {
      terrain[i][j] = ' ';
    }
  }

  for (let i = 0; i < yValues.length; i++) {
    const x = Math.floor((i / (yValues.length - 1)) * width);
    const y = height - 1 - Math.floor((yValues[i] / maxY) * height);
    terrain[y][x] = '#';
  }

  const terrainString = terrain.map((row) => row.join('')).join('\n');
  console.log(terrainString);
}
